language: erlang
otp_release:
   - 18.0
   - 18.1

sudo: false

addons:
  apt:
    packages:
      - build-essential

install:
  - "make"

script:
  - "make eunit"

notifications:
  email:
    recipients:
      - erocci-dev@ow2.org
    on_success: change
    on_failure: always
