sudo: required
dist: trusty

language: erlang
otp_release:
   - 18.1
   - 18.2.1

addons:
  apt:
    packages:
      - build-essential
      - dbus
      - python3
      - python3-gi
      - python3-dbus
      - python3-pycurl
      - libglib2.0-0

install:
  - "make"

script:
  - "make tests"

notifications:
  email:
    on_success: change
    on_failure: always
